name: de.ci.phe.red
title: de.ci.phe.red
collections_dir: site_collections
collections:
  research:
    output: true
  team:
    output: true 
   
url: http://de.ci.phe.red    
scholar:
  # style: apa
  group_by: year
  group_order: descending
  bibliography_template: bib